### ISSUE TITLE
Hex values appear in random places when using the in-line editor

### ISSUE THREAD

**Issue by mussorgsky** [konstantinkobs/brackets-colorHints#1]
When selecting the hinted colors from the in-line editor, they don't appear where you would expect them to. On the attached image you can see that the value 'c0ffee' appeared next to the head tag instead of the css.
![colorhints-bug](https://f.cloud.github.com/assets/6765359/2423440/7606921c-ab99-11e3-96f6-6948b51b42d7.png)
This is without any other add-ons installed.

**Comment by konstantinkobs** [comment]
So, I think, that the bugfix from the brackets team won't be in a near future, so I fixed this issue now with the same hack the CSSCodeHints extension is using.
